#ifndef __TSRN10_PTYPE_H__
#define __TSRN10_PTYPE_H__

#define TSRN10_MAX_PTYPE_SUPPORT	(2048)
static inline uint32_t
tsrn10_get_rx_parse_ptype(uint16_t ptype,  struct rte_mbuf *m __rte_unused)
{
	static const uint32_t type_table[TSRN10_MAX_PTYPE_SUPPORT]
		__rte_cache_aligned = {
		[0] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4,
		[1] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L2_ETHER_TIMESYNC,
		[2] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6,
		[3] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6,
		[4] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L4_TCP |
			RTE_PTYPE_L3_IPV4,
		[5] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_L4_TCP,
		[6] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_L4_TCP,
		[7] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6,
		[8] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_L4_SCTP,
		[9] = RTE_PTYPE_L4_SCTP | RTE_PTYPE_L2_ETHER |
			RTE_PTYPE_L3_IPV4,
		[10] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_L4_SCTP,
		[11] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L4_SCTP |
			RTE_PTYPE_L3_IPV6,
		[12] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_L4_UDP,
		[13] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_L4_UDP,
		[14] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_L4_UDP,
		[15] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_L4_UDP,
		/* Vxlan Tunnel */
		[512] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_VXLAN,
		[513] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_VXLAN,
		[514] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN,
		[515] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN,
		[516] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_TCP,
		[518] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_TCP,
		[520] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_SCTP,
		[522] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_SCTP,
		[524] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_UDP,
		[526] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_VXLAN | RTE_PTYPE_L4_UDP,
		/* Nvgre Tunnel */
		[1024] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_NVGRE,
		[1025] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_NVGRE,
		[1026] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_NVGRE,
		[1028] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_TCP,
		[1030] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_TCP,
		[1032] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_SCTP,
		[1034] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_SCTP,
		[1036] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV4 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_UDP,
		[1038] = RTE_PTYPE_L2_ETHER | RTE_PTYPE_L3_IPV6 |
			RTE_PTYPE_TUNNEL_NVGRE | RTE_PTYPE_L4_UDP,
	};
	return type_table[ptype];
}
#endif /* __TSRN10_PTYPE_H__ */
